$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: used-cars-train-env  # Provide the name for the environment
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created for training used car regressor model # Provide the name for the environment